#!/bin/sh

set -x
set -e

# find out which user is running the installation
# inst_user=`stat /dev/console | cut -f 5 -d ' '`
inst_user=$USER

# get arch
machine_arch=$(uname -p)

# chose binary
org_dir=$(pwd)
cd /Applications/Utilities/ChargerWallet\ Bridge/
if [ $machine_arch -eq "arm" ]; then
    mv chargerwalletd_darwin_arm64 chargerwalletd
    rm chargerwalletd_darwin_amd64
else
    mv chargerwalletd_darwin_amd64 chargerwalletd
    rm chargerwalletd_darwin_arm64
fi
# create log folder and set permissions
mkdir Logs
chmod 0777 Logs

agent_file=/Library/LaunchAgents/com.chargerwallet.bridge.chargerwalletd.plist

set +e
sudo -u $inst_user launchctl unload $agent_file
set -e
sudo -u $inst_user launchctl load $agent_file
