#!/bin/sh

set -x
set -e

# find out which user is running the installation
# inst_user=`stat /dev/console | cut -f 5 -d ' '`
inst_user=$USER

# cleanup legacy version
set +e
agent_file=/Library/LaunchAgents/com.bitcoinchargerwallet.chargerwalletBridge.chargerwalletd.plist
if [ -f "$agent_file" ]; then
    sudo -u $inst_user launchctl unload $agent_file
    sudo -u $inst_user killall chargerwalletd > /dev/null
    rm $agent_file
fi

if [ -d "/Applications/Utilities/ChargerWallet\ Bridge" ]; then
    rm -r /Applications/Utilities/ChargerWallet\ Bridge
fi

pkgutil --forget com.bitcoinchargerwallet.pkg.CHARGERWALLETBridge.uninstall
set -e

agent_file=/Library/LaunchAgents/com.chargerwallet.bridge.chargerwalletd.plist

set +e
sudo -u $inst_user launchctl unload $agent_file
sudo -u $inst_user killall chargerwalletd > /dev/null

rm $agent_file
rm -r /Applications/Utilities/ChargerWallet\ Bridge

pkgutil --forget com.chargerwallet.bridge

set -e
